---
# Try https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer
apiVersion: v1
kind: Service
metadata:
  name: scf-router-v1-0
spec:
  selector:
    app: scf-router-v1-0
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
