---
apiVersion: v1
kind: Service
metadata:
  name: scf-router-0-nodeport
  namespace: scf
  labels:
    fissile.cloudfoundry.org/az-index: "0"
    fissile.cloudfoundry.org/deployment-name: scf
    fissile.cloudfoundry.org/instance-group-name: router
    fissile.cloudfoundry.org/pod-ordinal: "0"
spec:
  ports:
  - name: router
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: router-ssl
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    fissile.cloudfoundry.org/az-index: "0"
    fissile.cloudfoundry.org/instance-group-name: router
    fissile.cloudfoundry.org/pod-ordinal: "0"
  type: NodePort
---
# Try https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scf-ingress
  namespace: scf
  # annotations:
  #   kubernetes.io/ingress.global-static-ip-name: "scf-drnic"
spec:
  backend:
    serviceName: scf-router-0-nodeport
    servicePort: 8000
